version: '3'

services:
  airflow:
    image: akirauwu/dsde-airflow
    volumes:
      - ./airflow:/opt/airflow
      - ./data:/opt/data
    ports:
      - "8080:8080"
    
    command: airflow standalone